### ISSUE TITLE
Define "Pipeline List" page

### ISSUE THREAD

**Issue by tobiasmcnulty** [caktus/etlman#43]
A/C

- [x] Use table layout in bootstrap: https://getbootstrap.com/docs/4.0/content/tables/
- [x] Define page listing pipelines in the current project, including columns:
     - [x] Name
     - [x] Input Type (DataInterface.type)
     - [x] Actions (includes edit link using https://fontawesome.com/v5/icons/edit?s=solid - goes to "Edit" workflow for the pipeline #12)
- [x] Update the `Pipeline` and `DataInterface` models as follows: add `input` `OneToOneFIeld` to `Pipeline` model, pointing to `DataInterface` model (use pipeline.input.type in the list view/template) - might need to be `null=True` for now

- [x] "Add pipeline" button at the top right of the page, goes to "New pipeline" workflow (#12)
- [x] Update the "New Project" wizard to redirect here on save redirect the user to the Pipeline List page (https://github.com/caktus/etlman/issues/42)
